### ISSUE TITLE
bold style not rendered

### ISSUE THREAD

**Issue by rpmcfong** [countableSet/antora-ui#16]
Looks like after the fix for #13, the bold face style is no longer being rendered correctly (Windows 10, Firefox 101.0.1). I discovered that _removing_ both of the font-weight styles below appear to fix the issue. I'm not sure if this is the correct fix or not; just an experimental result.

```
b, dt, strong, th {
  font-weight: 500;
  font-weight: var(--body-font-weight-bold);
}
```

Current
![image](https://user-images.githubusercontent.com/1176198/176030522-2b40eee0-edff-4074-bffd-c2c451ea2f28.png)

Fixed
![image](https://user-images.githubusercontent.com/1176198/176030759-ee155f23-7d57-4b4f-8ca3-8a4a8d5511dc.png)

**Comment by countableSet** [comment]
I'm tempted to say it's 'correct' just not 'visually correct' with the new font. 🙃 

GitHub uses a font weight of `600` for bold, which frankly to me doesn't look that **bold**.

<img width="1043" alt="Screen Shot 2022-06-30 at 4 13 57 PM" src="https://user-images.githubusercontent.com/226476/176793596-c006f6a3-03d7-42dd-88cf-aba9d6ed07d9.png">

k8s uses a weight of `700` which looks better, at least in light mode.

<img width="1172" alt="Screen Shot 2022-06-30 at 4 14 49 PM" src="https://user-images.githubusercontent.com/226476/176793712-68c57a35-53df-4783-960c-88299305ce4c.png">

700 looks like it might be close to what the default is for browsers, maybe we'll just set to that instead of removing it.


<img width="1305" alt="Screen Shot 2022-06-30 at 4 16 42 PM" src="https://user-images.githubusercontent.com/226476/176793861-e069f4ed-d0dc-4a71-9869-a91803ebc3ca.png">
<img width="1301" alt="Screen Shot 2022-06-30 at 4 16 37 PM" src="https://user-images.githubusercontent.com/226476/176793864-9fc75c34-c767-4318-b20a-f53b03597e62.png">
